"""
Turns hsk30.csv (from https://github.com/ivankra/hsk30) into a seed SQL file
for the `hsk_words` table, filtered to a single HSK level.

Usage:
    python build_seed.py --level 1 --input hsk30.csv --output seed_hsk1.sql

This is deliberately written as a plain, readable script rather than a package —
the goal is for you to be able to read every line and know exactly what it does.
"""

import argparse
import csv
import re
import sys

TONE_MAP = {
    "a": "āáǎà", "e": "ēéěè", "i": "īíǐì",
    "o": "ōóǒò", "u": "ūúǔù", "ü": "ǖǘǚǜ",
}


def toned_syllable_to_numbered(syllable: str) -> str:
    """Convert a single toned pinyin syllable like 'nǐ' into 'ni3'."""
    for base, toned_chars in TONE_MAP.items():
        for tone_index, toned_char in enumerate(toned_chars, start=1):
            if toned_char in syllable:
                plain = syllable.replace(toned_char, base)
                return f"{plain}{tone_index}"
    # No tone mark found (neutral tone) -> tone 5 by convention
    return f"{syllable}5" if syllable else syllable


def pinyin_to_numbered(pinyin: str) -> str:
    """Convert a full toned pinyin string ('nǐ hǎo') into numbered form ('ni3 hao3')."""
    syllables = pinyin.strip().split()
    return " ".join(toned_syllable_to_numbered(s) for s in syllables)


def escape_sql(value: str) -> str:
    return value.replace("'", "''")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--level", type=int, required=True, help="HSK level to extract, e.g. 1")
    parser.add_argument("--input", default="hsk30.csv", help="Path to the source CSV")
    parser.add_argument("--output", default="seed_hsk1.sql", help="Path to write the seed SQL")
    args = parser.parse_args()

    rows_written = 0
    try:
        with open(args.input, newline="", encoding="utf-8") as f_in, \
             open(args.output, "w", encoding="utf-8") as f_out:

            reader = csv.DictReader(f_in)
            f_out.write("-- Auto-generated by build_seed.py — do not edit by hand.\n")
            f_out.write("DELETE FROM hsk_words WHERE hsk_level = {};\n".format(args.level))

            for row in reader:
                # NOTE: column names below assume ivankra/hsk30's CSV header.
                # Print reader.fieldnames once and adjust if the schema differs.
                level = row.get("level") or row.get("hsk_level")
                if not level or int(re.sub(r"\D", "", level) or 0) != args.level:
                    continue

                hanzi = row.get("simplified") or row.get("hanzi", "")
                pinyin = row.get("pinyin", "")
                meaning = row.get("english") or row.get("meaning", "")
                pos = row.get("pos", "")
                numbered = pinyin_to_numbered(pinyin)

                f_out.write(
                    "INSERT INTO hsk_words (hanzi, pinyin, pinyin_numbered, meaning_en, "
                    "hsk_level, part_of_speech) VALUES ('{}', '{}', '{}', '{}', {}, '{}');\n".format(
                        escape_sql(hanzi), escape_sql(pinyin), escape_sql(numbered),
                        escape_sql(meaning), args.level, escape_sql(pos),
                    )
                )
                rows_written += 1

        print(f"Wrote {rows_written} rows for HSK level {args.level} to {args.output}")
    except FileNotFoundError:
        print(f"Could not find {args.input} — download it from the ivankra/hsk30 repo first.",
              file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
